# Generated by Django 5.0.4 on 2024-10-19 19:52

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_random_code, max_length=8, unique=True)),
                ('name', models.CharField(default='Room Name', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_controls', models.BooleanField(default=False)),
                ('current_time', models.FloatField(default=0.0)),
                ('is_playing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('file', models.FileField(upload_to='tracks')),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, unique=True)),
                ('control_permission', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='api.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.track'),
        ),
    ]
